service: github-trending-reporter

plugins:
  - serverless-webpack
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 7

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-northeast-2
  lambdaHashingVersion: 20201221
  timeout: 28
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  environment:
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}
    SLACK_TRENDING_CHANNEL: ${env:SLACK_TRENDING_CHANNEL}
    SLACK_OWNER_CHANNEL: ${env:SLACK_OWNER_CHANNEL}
    SCHEDULE: ${env:SCHEDULE}

functions:
  reportTrending:
    handler: src/lambda.handleReportTrending
    events:
      - httpApi: POST /trending/{language}/{period}
  reportOwner:
    handler: src/lambda.handleReportOwner
    events:
      - httpApi: POST /owner/{owner}
  reportByScheduler:
    handler: src/lambda.handleSchedulerByApi
    events:
      - httpApi: POST /
  onSchedule:
    handler: src/lambda.handleScheduler
    timeout: 120
    events:
      - schedule: cron(0 1 * * ? *)
