service: github-trending-reporter

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-northeast-2

package:
  exclude:
    - "**/*"
  include:
    - "src/*.js"

functions:
  report:
    handler: src/lambda.handler
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{language}/{period}
          method: post
      - schedule: cron(0 9 * * ? *)
    environment:
      SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}
