service: github-trending-reporter

plugins:
  - serverless-esbuild
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 7
  esbuild:
    bundle: true
    minify: true
    packager: "pnpm"
    watch:
      pattern: "src/**/*.ts"

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: ap-northeast-2
  timeout: 28
  memorySize: 512
  apiGateway:
    shouldStartNameWithService: true
  environment:
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}
    SLACK_TRENDING_CHANNEL: ${env:SLACK_TRENDING_CHANNEL}
    SLACK_OWNER_CHANNEL: ${env:SLACK_OWNER_CHANNEL}
    SCHEDULE: ${env:SCHEDULE}

functions:
  reportTrending:
    handler: src/lambda.handleReportTrending
    events:
      - httpApi: POST /trending/{language}/{period}
  reportOwner:
    handler: src/lambda.handleReportOwner
    events:
      - httpApi: POST /owner/{owner}
  reportByScheduler:
    handler: src/lambda.handleSchedulerByApi
    events:
      - httpApi: POST /
  reportByTrendingScheduler:
    handler: src/lambda.handleTrendingSchedulerByApi
    events:
      - httpApi: POST /trending
  reportByOwnerScheduler:
    handler: src/lambda.handleOwnerSchedulerByApi
    events:
      - httpApi: POST /owner
  onSchedule:
    handler: src/lambda.handleScheduler
    timeout: 120
    events:
      - schedule: cron(0 1 * * ? *)
