service: github-trending-reporter

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-northeast-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}
    SCHEDULE: ${env:SCHEDULE}

functions:
  report:
    handler: src/lambda.handlerReport
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{language}/{period}
          method: post
  reportToday:
    handler: src/lambda.handlerReportToday
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /
          method: post
      - schedule: cron(0 1 * * ? *)
