service: github-trending-reporter

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-northeast-2
  environment:
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}
    SCHEDULE: ${env:SCHEDULE}

package:
  exclude:
    - "**/*"
  include:
    - "src/*.js"

functions:
  report:
    handler: src/lambda.handlerReport
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{language}/{period}
          method: post
  reportToday:
    handler: src/lambda.handlerReportToday
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /
          method: post
      - schedule: cron(0 1 * * ? *)
